OUTPUT_DIR: "output/zala"
DEBUG_RUN: true
FONTSIZE: 13
MOT:
  REID_MODEL_OPTS: "models/resnet50_mixstyle/opts.yaml"
  REID_MODEL_CKPT: "models/resnet50_mixstyle/net_19.pth"
  REID_FP16: false
  REID_BATCHSIZE: 1
  DETECTOR: "yolov5x6"
  TRACKER: "bytetrack_iou"
  MIN_FRAMES: 10
  SHOW: false
  VIDEO_OUTPUT: false
  STATIC_ATTRIBUTES:
    - color: "models/color_svm.pkl"
    - type: "models/type_svm.pkl"
  ATTRIBUTE_INFER_BATCHSIZE: 1
  REFINE: false
MTMC:
  CAMERA_LAYOUT: 'config/zala/mtmc_camera_layout.txt'
  LINKAGE: 'average'
  MIN_SIM: 0.5
EXPRESS:
  FINAL_VIDEO_OUTPUT: true
  CAMERAS:
    - "video": "datasets/Zalaegerszeg/balaton.mp4"
      "detection_mask": "assets/zala/balaton_mask.jpg"
      "calibration": "config/zala/calibration_balaton.txt"
    - "video": "datasets/Zalaegerszeg/gasparich_utca.mp4"
      "detection_mask": "assets/zala/gasparich_mask.jpg"
    - "video": "datasets/Zalaegerszeg/kormend.mp4"
      "detection_mask": "assets/zala/kormend_mask.jpg"
    - "video": "datasets/Zalaegerszeg/bevasarlokozpont.mp4"
      "detection_mask": "assets/zala/bevasarlokozpont_mask.jpg"


   
      
