OUTPUT_DIR: "output/zala_express"
MOT:
 REID_MODEL_OPTS: "reid/vehicle_reid/model/new_resnet_verzal_ce/opts.yaml"
 REID_MODEL_CKPT: "reid/vehicle_reid/model/new_resnet_verzal_ce/net_19.pth"
 REID_FP16: false
 REID_BATCHSIZE: 1
 DETECTOR: "yolov5x6"
 TRACKER: "bytetrack_iou"
 SHOW: false
 VIDEO_OUTPUT: false
 STATIC_ATTRIBUTES:
   - color: "models/color_net_verzal.pth"
   - type: "models/type_net_verzal_2.pth"
 ATTRIBUTE_INFER_BATCHSIZE: 1
 REFINE: false
MTMC:
  CAMERA_LAYOUT: 'config/zala/mtmc_camera_layout.txt'
  LINKAGE: 'average'
  MIN_SIM: 0.5
EXPRESS:
  FINAL_VIDEO_OUTPUT: false
  CAMERAS:
    - "video": "datasets/Zalaegerszeg/balaton.mp4"
      "detection_mask": "assets/balaton_mask.jpg"
      "zone_mask_dir": "assets/zones/balaton/"
      "valid_zonepaths":
        - "^(1,)+(0(,0)*,)?2(,2)*$"
        - "^(2,)+(0(,0)*,)?1(,1)*$"
        - "^2(,2)*$"
    - "video": "datasets/Zalaegerszeg/gasparich_utca.mp4"
      "detection_mask": "assets/gasparich_mask.jpg"
      "zone_mask_dir": "assets/zones/gasparich/"
      "valid_zonepaths":
        - "^(1,)+(0(,0)*,)?2(,2)*$"
        - "^(2,)+(0(,0)*,)?1(,1)*$"
        - "^2(,2)*$"
    - "video": "datasets/Zalaegerszeg/kormend.mp4"
      "detection_mask": "assets/kormend_mask.jpg"
      "zone_mask_dir": "assets/zones/kormend/"
      "valid_zonepaths":
        - "^(1,)+(0(,0)*,)?2(,2)*$"
        - "^(2,)+(0(,0)*,)?1(,1)*$"
        - "^2(,2)*$"
    - "video": "datasets/Zalaegerszeg/bevasarlokozpont.mp4"
      "detection_mask": "assets/bevasarlokozpont_mask.jpg"
      "zone_mask_dir": "assets/zones/bevasarlokozpont/"
      "valid_zonepaths":
        - "^(1,)+(0(,0)*,)?2(,2)*$"
        - "^(2,)+(0(,0)*,)?1(,1)*$"
        - "^2(,2)*$"

   
      
