OUTPUT_DIR: "output/zala_gasparich"
FONTSIZE: 13
DEBUG_RUN: false
MOT:
  VIDEO: "datasets/Zalaegerszeg/gasparich_utca.mp4"
  REID_MODEL_OPTS: "models/resnet50_mixstyle/opts.yaml"
  REID_MODEL_CKPT: "models/resnet50_mixstyle/net_19.pth"
  REID_FP16: false
  REID_BATCHSIZE: 1
  DETECTOR: "yolov5x6"
  DETECTION_MASK: "assets/zala/gasparich_mask.jpg"
  TRACKER: "bytetrack_iou"
  SHOW: false
  VIDEO_OUTPUT: true
  STATIC_ATTRIBUTES:
    - color: "models/color_svm.pkl"
    - type: "models/type_svm.pkl"
  ZONE_MASK_DIR: "assets/zones/gasparich/"
  VALID_ZONEPATHS:
    - "^(1,)+(0(,0)*,)?2(,2)*$"
    - "^(2,)+(0(,0)*,)?1(,1)*$"
    - "^2(,2)*$"
