OUTPUT_DIR: "output/zala_kormend"
FONTSIZE: 13
DEBUG_RUN: false
MOT:
  VIDEO: "datasets/Zalaegerszeg/kormend.mp4"
  REID_MODEL_OPTS: "models/resnet50_mixstyle/opts.yaml"
  REID_MODEL_CKPT: "models/resnet50_mixstyle/net_19.pth"
  CALIBRATION: "config/zala/calibration_balaton.txt"
  REID_FP16: false
  REID_BATCHSIZE: 1
  DETECTOR: "yolov5x6"
  DETECTION_MASK: "assets/zala/kormend_mask.jpg"
  TRACKER: "bytetrack_iou"
  MIN_FRAMES: 5
  SHOW: false
  VIDEO_OUTPUT: true
  STATIC_ATTRIBUTES:
   - color: "models/color_svm.pkl"
   - type: "models/type_svm.pkl"
  ATTRIBUTE_INFER_BATCHSIZE: 1
  ZONE_MASK_DIR: "assets/zones/kormend/"
  VALID_ZONEPATHS:
    - "^(1,)+(0(,0)*,)?2(,2)*$"
    - "^(2,)+(0(,0)*,)?1(,1)*$"
    - "^2(,2)*$"

   
