OUTPUT_DIR: "output/ctic_4cameras_test"
DEBUG_RUN: false
FONTSIZE: 15
MOT:
  REID_MODEL_OPTS: "models/res-ibn/opts.yaml"
  REID_MODEL_CKPT: "models/res-ibn/net_19.pth"
  REID_FP16: false
  REID_BATCHSIZE: 1
  DETECTOR: "yolov5s"
  TRACKER: "deepsort"
  MIN_FRAMES: 5
  SHOW: false
  VIDEO_OUTPUT: true
  ATTRIBUTE_INFER_BATCHSIZE: 1
  REFINE: false
MTMC:
  CAMERA_LAYOUT: 'config/cityflow/s02_camera_layout_v3.txt'
  LINKAGE: 'mean_feature'
  MIN_SIM: 0.3
EXPRESS:
  FINAL_VIDEO_OUTPUT: true
  CAMERAS:
    - "video": "datasets/hls_ctic/video1/v1_20.avi" 
      "calibration": "datasets/ctic_1floor/validation/S02/c006/calibration.txt"
    - "video": "datasets/hls_ctic/video2/v2_20.avi"
      "calibration": "datasets/ctic_1floor/validation/S02/c007/calibration.txt"
    - "video": "datasets/hls_ctic/video3/v3_20.avi"
      "calibration": "datasets/ctic_1floor/validation/S02/c008/calibration.txt"
    - "video": "datasets/hls_ctic/video4/v4_20.avi"
      "calibration": "datasets/ctic_1floor/validation/S02/c009/calibration.txt"

