OUTPUT_DIR: "output/cityflow_s02_c006"
FONTSIZE: 24
DEBUG_RUN: true
MOT:
  VIDEO: "datasets/cityflow_track3/validation/S02/c006/vdo.avi"
  REID_MODEL_OPTS: "reid/vehicle_reid/model/resnet50_cityflow/opts.yaml"
  REID_MODEL_CKPT: "reid/vehicle_reid/model/resnet50_cityflow/net_15.pth"
  CALIBRATION: "datasets/cityflow_track3/validation/S02/c006/calibration.txt"
  REID_FP16: false
  REID_BATCHSIZE: 1
  DETECTOR: "yolov5x6"
  DETECTION_MASK: "assets/cityflow/c006_mask.jpg"
  TRACKER: "bytetrack_iou"
  MIN_FRAMES: 5
  SHOW: true
  VIDEO_OUTPUT: true
  STATIC_ATTRIBUTES:
    - color: "models/color_net_verzal.pth"
    - type: "models/type_net_verzal_2.pth"
  ATTRIBUTE_INFER_BATCHSIZE: 1
  REFINE: false
   
