OUTPUT_DIR: "output/cityflow_mtmc_eval"
MTMC:
  CAMERA_LAYOUT: 'config/cityflow/mtmc_camera_layout.txt'
  PICKLED_TRACKLETS:
    - "output/cityflow_s02_city/0_vdo/vdo.pkl"
    - "output/cityflow_s02_city/1_vdo/vdo.pkl"
    - "output/cityflow_s02_city/2_vdo/vdo.pkl"
    - "output/cityflow_s02_city/3_vdo/vdo.pkl"
  LINKAGE: 'single'
  MIN_SIM: 0.52
EVAL:
  MIN_IOU: 0.34
  IGNORE_FP: true
  DROP_SINGLE_CAM: false
  GROUND_TRUTHS:
    - "datasets/cityflow_track3/validation/S02/c006/gt/gt.txt"
    - "datasets/cityflow_track3/validation/S02/c007/gt/gt.txt"
    - "datasets/cityflow_track3/validation/S02/c008/gt/gt.txt"
    - "datasets/cityflow_track3/validation/S02/c009/gt/gt.txt"
