OUTPUT_DIR: "output/cityflow_s01_mtmc_eval"
MTMC:
  CAMERA_LAYOUT: 'config/cityflow/s01_camera_layout.txt'
  PICKLED_TRACKLETS:
    - "output/cityflow_s01/0_vdo/mot.pkl"
    - "output/cityflow_s01/1_vdo/mot.pkl"
    - "output/cityflow_s01/2_vdo/mot.pkl"
    - "output/cityflow_s01/3_vdo/mot.pkl"
    - "output/cityflow_s01/4_vdo/mot.pkl"
  LINKAGE: 'single'
  MIN_SIM: 0.5
EVAL:
  MIN_IOU: 0.34
  IGNORE_FP: true
  DROP_SINGLE_CAM: true
  GROUND_TRUTHS:
    - "datasets/cityflow_track3/train/S01/c001/gt/gt.txt"
    - "datasets/cityflow_track3/train/S01/c002/gt/gt.txt"
    - "datasets/cityflow_track3/train/S01/c003/gt/gt.txt"
    - "datasets/cityflow_track3/train/S01/c004/gt/gt.txt"
    - "datasets/cityflow_track3/train/S01/c005/gt/gt.txt"
