MOT:
 VIDEO: "datasets/highway.mp4"
 REID_MODEL_OPTS: "reid/vehicle_reid/model/resnet_ibn/opts.yaml"
 REID_MODEL_CKPT: "reid/vehicle_reid/model/resnet_ibn/net_11.pth"
 REID_FP16: true
 DETECTOR: "yolov5x6"
 DETECTION_MASK: "assets/highway_mask.jpg"
 SHOW: true
 VIDEO_OUTPUT: "output/highway_tracked.mp4"
 CSV_RESULT_PATH: "output/highway_results.csv"
 RESULT_PATH: "output/highway_results.pkl"
 REID_BATCHSIZE: 1
 STATIC_FEATURES:
   - color: "models/resnet18-color_veriwild.pt"
   - type: "models/resnet18-type_veriwild.pt"
 STATIC_FEATURE_BATCHSIZE: 1
 ZONE_MASK_DIR: "assets/zones/highway/"
 VALID_ZONEPATHS:
   - "^(1,)+(0(,0)*,)?2(,2)*$"
   - "^(4,)+(0(,0)*,)?3(,3)*$"
 REFINE: false
   
