MOT:
 VIDEO: "datasets/Zalaegerszeg/gasparich_utca.mp4"
 REID_MODEL_OPTS: "reid/vehicle_reid/model/resnet_ibn/opts.yaml"
 REID_MODEL_CKPT: "reid/vehicle_reid/model/resnet_ibn/net_11.pth"
 REID_FP16: true
 REID_BATCHSIZE: 16
 DETECTOR: "yolov5x6"
 DETECTION_MASK: "assets/gasparich_mask.jpg"
 SHOW: false
 CSV_RESULT_PATH: "output/gasparich_results.csv"
 RESULT_PATH: "output/gasparich_results.pkl"
 STATIC_FEATURES:
   color: "models/resnet18-color_veriwild.pt"
   type: "models/resnet18-type_veriwild.pt"
 STATIC_FEATURE_BATCHSIZE: 1
 ZONE_MASK_DIR: "assets/zones/gasparich/"
 VALID_ZONEPATHS:
   - "^(1,)+(0(,0)*,)?2(,2)*$"
   - "^(2,)+(0(,0)*,)?1(,1)*$"
   - "^2(,2)*$"
 REFINE: false
   
