OUTPUT_DIR: "output/cityflow_s01_c001"
FONTSIZE: 15
DEBUG_RUN: false
MOT:
  VIDEO: "datasets/cityflow_track3/train/S01/c001/vdo.avi"
  REID_MODEL_OPTS: "models/resnet50_mixstyle/opts.yaml"
  REID_MODEL_CKPT: "models/resnet50_mixstyle/net_19.pth"
  CALIBRATION: "datasets/cityflow_track3/train/S01/c001/calibration.txt"
  REID_FP16: false
  REID_BATCHSIZE: 1
  DETECTOR: "yolov5x6"
  DETECTION_MASK: "datasets/cityflow_track3/train/S01/c001/roi.jpg"
  TRACKER: "bytetrack_iou"
  MIN_FRAMES: 5
  SHOW: false
  VIDEO_OUTPUT: true
  STATIC_ATTRIBUTES:
    - color: "models/color_svm.pkl"
    - type: "models/type_svm.pkl"
  ATTRIBUTE_INFER_BATCHSIZE: 1
  REFINE: false
EVAL:
  MIN_IOU: 0.34
  IGNORE_FP: true
  GROUND_TRUTHS:
    - "datasets/cityflow_track3/train/S01/c001/gt/gt.txt"

