OUTPUT_DIR: "output/hls_test2"
FONTSIZE: 11
MOT:
  VIDEO: "datasets/streaming_test/videoF2.mp4"
  REID_MODEL_OPTS: "models/res-ibn/opts.yaml"
  REID_MODEL_CKPT: "models/res-ibn/net_19.pth"
  #CALIBRATION: "config/examples/highway_calibration.txt"
  REID_FP16: false
  REID_BATCHSIZE: 1
  DETECTOR: "yolov5n"
  TRACKER: "deepsort"
  DETECTION_MASK: "assets/highway_mask.jpg"
  SHOW: true
  VIDEO_OUTPUT: true
  ATTRIBUTE_INFER_BATCHSIZE: 1
  REFINE: false
